# Generated by Django 4.2.6 on 2023-11-22 04:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_ean'),
    ]

    operations = [
        migrations.AddField(
            model_name='ean',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ean',
            name='is_loaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ean',
            name='ean_code',
            field=models.CharField(max_length=30),
        ),
    ]
