# Generated by Django 4.2.6 on 2023-11-29 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_ean_created_at_ean_is_loaded_alter_ean_ean_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lbi',
            name='Number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
