# Generated by Django 4.2.6 on 2023-11-29 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0007_eanadmin_lbiadmin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='Cedula',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
