# Generated by Django 4.2.6 on 2023-12-01 05:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0008_remove_customuser_cedula_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='ean',
            name='colaborador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
